# Generated by Django 5.0.3 on 2024-03-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiningData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.DecimalField(decimal_places=6, max_digits=9)),
                ('cu_grade', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
