# Generated by Django 5.0.3 on 2024-03-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miningdata',
            old_name='location',
            new_name='location_latitude',
        ),
        migrations.AddField(
            model_name='miningdata',
            name='location_longitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
    ]
